/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.accurx.reliabledownloader;

import java.io.IOException;
import java.util.concurrent.ExecutionException;

public class App {

    public static void main(String[] args) throws IOException, ExecutionException, InterruptedException {
        var exampleUrl = "https://installer.demo.accurx.com/chain/3.182.57641.0/accuRx.Installer.Local.msi";
        var exampleFilePath = "downloadedContent/myfirstdownload.msi";

        var fileDownloader = new MyFileDownloader();
        fileDownloader.DownloadFile(exampleUrl, exampleFilePath, (progress) -> System.out.println("Percent progress is " + progress));
    }
}
